//
// Created by Dominic Gallo on 5/2/22.
//

#ifndef CSTP_SERVER_SERVER_STATE_H
#define CSTP_SERVER_SERVER_STATE_H
enum Server_State{
    SS_AWAITING_CONNECTION,
    SS_PARSING_CLIENT,
    SS_SERIALIZING_REQUEST,
    SS_ROUTING_REQUEST,
    SS_BUILDING_RESPONSE,
    SS_WRITING_RESPONSE,
    SS_EXIT

};
#endif //CSTP_SERVER_SERVER_STATE_H
